//! National Center for Education Statistics.
//!
//! The Common Core of Data LEA directory, thirty years of it, in two formats and fourteen
//! fixed-width vintages. It is the join key for everything federal: without the NCES-to-IRN map
//! no federal series can be attached to an Ohio district.

use super::{Connector, Format, Source, Status};

pub(super) const CCD: Connector = Connector {
    key: "nces-ccd",
    publisher: "National Center for Education Statistics",
    feeds: &["education-agency"],
    status: Status::Wired {
        still_blocked: Some(
            "wired for every school year the directory publishes with an Ohio slice this \
             reader can take, 1994-95 through 2023-24. The nine years before 1994-95 exist \
             and are not held: 1986-87 through 1993-94 are the same fixed-width family, and \
             nothing consumes them. The identifier-change history is still not derivable \
             from this source, and thirty years of it now say so rather than sixteen: Ohio \
             has never once filed the status code that marks a consolidation",
        ),
    },
    note: "A corpus spanning 1851 to the present is a panel whose members change, and a \
           long series assembled without accounting for consolidation is silently wrong. \
           What the directory settles is which agencies existed when, and what it refuses to \
           settle is why any of them stopped.",
    sources: &[
        Source {
            key: "ccd-lea-directory-9495",
            title: None,
            url: "https://nces.ed.gov/ccd/data/zip/pau94datr.zip",
            filename: "ccd-lea-directory-9495.zip",
            format: Format::Zip,
            catalog: Some("nces-ccd-lea-directory"),
            fixtures: &[crate::fixtures::CCD_DIRECTORY_FIXTURE],
            note: "School year 1994-95, and the oldest year this repository holds. Fixed-width, 1,030 bytes a record, no header. The revision is the only edition served: `pau94data.zip` is a 404 and `pau94datr.zip` is what the publisher links. 790 Ohio agencies, every one of them filed `1 No significant boundary change` — the first year held is the one year with no departure in it.",
        },
        Source {
            key: "ccd-lea-directory-9596",
            title: None,
            url: "https://nces.ed.gov/ccd/data/zip/pau95data.zip",
            filename: "ccd-lea-directory-9596.zip",
            format: Format::Zip,
            catalog: Some("nces-ccd-lea-directory"),
            fixtures: &[crate::fixtures::CCD_DIRECTORY_FIXTURE],
            note: "School year 1995-96. The file named `pau95` is the year *after* the file named `pau94`, which is the trap in this whole era: the archive is keyed on the year the survey closed and the directory describes the year it opened. Its own layout document settles it, saying `1995-96` in the heading and again in the sentence beneath. Nine agencies here are flagged closed, and all nine are county boards of education.",
        },
        Source {
            key: "ccd-lea-directory-9697",
            title: None,
            url: "https://nces.ed.gov/ccd/data/zip/pau96data.zip",
            filename: "ccd-lea-directory-9697.zip",
            format: Format::Zip,
            catalog: Some("nces-ccd-lea-directory"),
            fixtures: &[crate::fixtures::CCD_DIRECTORY_FIXTURE],
            note: "School year 1996-97. The layout document changes shape without the file changing: 1994-95 and 1995-96 print name, type, position, size, and this one prints name, size, position, type. The record is byte-for-byte the same 1,030.",
        },
        Source {
            key: "ccd-lea-directory-9798",
            title: None,
            url: "https://nces.ed.gov/ccd/data/zip/pau97data.zip",
            filename: "ccd-lea-directory-9798.zip",
            format: Format::Zip,
            catalog: Some("nces-ccd-lea-directory"),
            fixtures: &[crate::fixtures::CCD_DIRECTORY_FIXTURE],
            note: "School year 1997-98, and the last year before Ohio has a community school. Type 7 here is 23 agencies and every one of them is a county board's data-processing centre. Four years later type 7 is 249 and the composition is the opposite.",
        },
        Source {
            key: "ccd-lea-directory-9899",
            title: None,
            url: "https://nces.ed.gov/ccd/data/zip/ag981c_dat.zip",
            filename: "ccd-lea-directory-9899.zip",
            format: Format::Zip,
            catalog: Some("nces-ccd-lea-directory"),
            fixtures: &[crate::fixtures::CCD_DIRECTORY_FIXTURE],
            note: "School year 1998-99. The record shrinks to 722 bytes and every column this reader takes moves at once: the name field widens from 30 to 60, the agency type goes from byte 121 to 234, and the status from 162 to 280. Nothing before this year can be read with the offsets of anything after it.",
        },
        Source {
            key: "ccd-lea-directory-9900",
            title: None,
            url: "https://nces.ed.gov/ccd/data/zip/ag991b_dat.zip",
            filename: "ccd-lea-directory-9900.zip",
            format: Format::Zip,
            catalog: Some("nces-ccd-lea-directory"),
            fixtures: &[crate::fixtures::CCD_DIRECTORY_FIXTURE],
            note: "School year 1999-2000, second revision. Its layout document's own header says `FILE NAME = ag991a.dat` while the record count beneath it is this file's, which is why the layout is read for offsets and never for identity. `ag991a_dat.zip` is still served; its Ohio rows are identical in all five columns taken here.",
        },
        Source {
            key: "ccd-lea-directory-0001",
            title: None,
            url: "https://nces.ed.gov/ccd/data/zip/ag001a_dat.zip",
            filename: "ccd-lea-directory-0001.zip",
            format: Format::Zip,
            catalog: Some("nces-ccd-lea-directory"),
            fixtures: &[crate::fixtures::CCD_DIRECTORY_FIXTURE],
            note: "School year 2000-01. The record grows a byte, to 723, and the status column moves with it to 281. A one-byte drift is the failure this era is most likely to produce quietly, because the byte to the left is the metropolitan indicator and its values are also small integers.",
        },
        Source {
            key: "ccd-lea-directory-0102",
            title: None,
            url: "https://nces.ed.gov/ccd/data/zip/ag011a_dat.zip",
            filename: "ccd-lea-directory-0102.zip",
            format: Format::Zip,
            catalog: Some("nces-ccd-lea-directory"),
            fixtures: &[crate::fixtures::CCD_DIRECTORY_FIXTURE],
            note: "School year 2001-02. 725 bytes, and the member inside the archive is `AG011A.DAT` in capitals where its neighbours are lower case. The year Ohio's sixteen special-education regional resource centres and its twenty-four data-processing centres all leave the directory at once.",
        },
        Source {
            key: "ccd-lea-directory-0203",
            title: None,
            url: "https://nces.ed.gov/ccd/data/zip/ag021a_dat.zip",
            filename: "ccd-lea-directory-0203.zip",
            format: Format::Zip,
            catalog: Some("nces-ccd-lea-directory"),
            fixtures: &[crate::fixtures::CCD_DIRECTORY_FIXTURE],
            note: "School year 2002-03. 729 bytes, status at 284. Its layout document runs `BOUND02`'s entire entry onto the end of the line above it, so a parser that anchors variable names to the start of a line does not find the column at all — and the two neighbouring years put it somewhere else, so guessing is not available either.",
        },
        Source {
            key: "ccd-lea-directory-0304",
            title: None,
            url: "https://nces.ed.gov/ccd/data/zip/ag031b_dat.zip",
            filename: "ccd-lea-directory-0304.zip",
            format: Format::Zip,
            catalog: Some("nces-ccd-lea-directory"),
            fixtures: &[crate::fixtures::CCD_DIRECTORY_FIXTURE],
            note: "School year 2003-04. Named `_dat` and holding `ag031b.txt`, which is fixed-width regardless of what it is called. **Its layout document states the status column's position wrongly** — 281, which is the metropolitan indicator's — and states it a second time as 384. The true position is 284, and this repository takes it from the file rather than the document: see `fixtures::CCD_FIXED_WIDTH`. `ag031a_dat.zip` is still served and its Ohio rows agree in all five columns.",
        },
        Source {
            key: "ccd-lea-directory-0405",
            title: None,
            url: "https://nces.ed.gov/ccd/data/zip/ag041c_dat.zip",
            filename: "ccd-lea-directory-0405.zip",
            format: Format::Zip,
            catalog: Some("nces-ccd-lea-directory"),
            fixtures: &[crate::fixtures::CCD_DIRECTORY_FIXTURE],
            note: "School year 2004-05, third revision. The record almost halves, to 519 bytes, because the dropout and completer counts leave the agency file. Nothing this reader takes moves. `ag041a_dat.zip` is still served and agrees on Ohio.",
        },
        Source {
            key: "ccd-lea-directory-0506",
            title: None,
            url: "https://nces.ed.gov/ccd/data/zip/ag051a_dat.zip",
            filename: "ccd-lea-directory-0506.zip",
            format: Format::Zip,
            catalog: Some("nces-ccd-lea-directory"),
            fixtures: &[crate::fixtures::CCD_DIRECTORY_FIXTURE],
            note: "School year 2005-06. Its layout document is the previous year's with the heading changed: the sentence beneath still reads *\"data for the school year 2004-05\"* and the observation count is still 18,085, where this file has 18,213 records. The record length it gives, 519, is right — which is the worst arrangement, because the parts that are wrong are the parts a reader would use to check the parts that are not.",
        },
        Source {
            key: "ccd-lea-directory-0607",
            title: None,
            url: "https://nces.ed.gov/ccd/data/zip/ag061c_dat.zip",
            filename: "ccd-lea-directory-0607.zip",
            format: Format::Zip,
            catalog: Some("nces-ccd-lea-directory"),
            fixtures: &[crate::fixtures::CCD_DIRECTORY_FIXTURE],
            note: "School year 2006-07, and the last fixed-width year. 530 bytes; latitude, longitude and a congressional district code arrive ahead of the status column and push it to 309. The year the agency type stops distinguishing a local district from a component of a supervisory union: Ohio's 238 type 1 and 377 type 2 become 614 type 1, with no agency joining or leaving.",
        },
        Source {
            key: "ccd-lea-directory-0708",
            title: None,
            url: "https://nces.ed.gov/ccd/data/zip/ag071b_txt.zip",
            filename: "ccd-lea-directory-0708.zip",
            format: Format::Zip,
            catalog: Some("nces-ccd-lea-directory"),
            fixtures: &[crate::fixtures::CCD_DIRECTORY_FIXTURE],
            note: "School year 2007-08, and not fixed-width at all — tab-delimited with a header, exactly like 2008-09. It reads through the alias table with nothing added: `STID07`, `NAME07`, `TYPE07` and `BOUND07` were listed there before any wired year used them, because the aliases are per naming convention rather than per year.",
        },
        Source {
            key: "ccd-lea-directory-0809",
            title: None,
            url: "https://nces.ed.gov/ccd/data/zip/ag081a_txt.zip",
            filename: "ccd-lea-directory-0809.zip",
            format: Format::Zip,
            catalog: Some("nces-ccd-lea-directory"),
            fixtures: &[crate::fixtures::CCD_DIRECTORY_FIXTURE],
            note: "School year 2008-09. Tab-delimited with a header, and the columns carry a year suffix: `STID08`, `BOUND08`, `TYPE08`. This is also the one year with no charter column at all, which is why agency type rather than a charter flag is what this reader keys on.",
        },
        Source {
            key: "ccd-lea-directory-0910",
            title: None,
            url: "https://nces.ed.gov/ccd/data/zip/ag092a_txt.zip",
            filename: "ccd-lea-directory-0910.zip",
            format: Format::Zip,
            catalog: Some("nces-ccd-lea-directory"),
            fixtures: &[crate::fixtures::CCD_DIRECTORY_FIXTURE],
            note: "School year 2009-10. The second revision. `ag091a_txt.zip` is the first and differs from it in 42 rows nationally, none of them Ohio's.",
        },
        Source {
            key: "ccd-lea-directory-1011",
            title: None,
            url: "https://nces.ed.gov/ccd/data/zip/ag102a_txt.zip",
            filename: "ccd-lea-directory-1011.zip",
            format: Format::Zip,
            catalog: Some("nces-ccd-lea-directory"),
            fixtures: &[crate::fixtures::CCD_DIRECTORY_FIXTURE],
            note: "School year 2010-11. The second revision again, and the year the column names lose their suffix: `STID` and `BOUND` from here to 2013-14.",
        },
        Source {
            key: "ccd-lea-directory-1112",
            title: None,
            url: "https://nces.ed.gov/ccd/data/zip/ag111a_txt.zip",
            filename: "ccd-lea-directory-1112.zip",
            format: Format::Zip,
            catalog: Some("nces-ccd-lea-directory"),
            fixtures: &[crate::fixtures::CCD_DIRECTORY_FIXTURE],
            note: "School year 2011-12. The archive is named `ag111a_txt` and the file inside it is `ag111a_supp.txt`, which is the naming the next two years use in the URL as well.",
        },
        Source {
            key: "ccd-lea-directory-1213",
            title: None,
            url: "https://nces.ed.gov/ccd/data/zip/ag121a_supp_txt.zip",
            filename: "ccd-lea-directory-1213.zip",
            format: Format::Zip,
            catalog: Some("nces-ccd-lea-directory"),
            fixtures: &[crate::fixtures::CCD_DIRECTORY_FIXTURE],
            note: "School year 2012-13. The year `LSTATE` stops agreeing with `FIPST`: LEAID 3901497, Urban Pathways of Youngstown, is filed with `FIPST=39` and `LSTATE=PA`. Ohio is selected on `FIPST` throughout for that reason.",
        },
        Source {
            key: "ccd-lea-directory-1314",
            title: None,
            url: "https://nces.ed.gov/ccd/data/zip/ag131a_supp_txt.zip",
            filename: "ccd-lea-directory-1314.zip",
            format: Format::Zip,
            catalog: Some("nces-ccd-lea-directory"),
            fixtures: &[crate::fixtures::CCD_DIRECTORY_FIXTURE],
            note: "School year 2013-14. The last year of the tab-delimited era.",
        },
        Source {
            key: "ccd-lea-directory-1415",
            title: None,
            url: "https://nces.ed.gov/ccd/data/zip/ccd_lea_029_1415_w_0216161ar_txt.zip",
            filename: "ccd-lea-directory-1415.zip",
            format: Format::Zip,
            catalog: Some("nces-ccd-lea-directory"),
            fixtures: &[crate::fixtures::CCD_DIRECTORY_FIXTURE],
            note: "School year 2014-15. The revision, not the original. `..._0216161a_txt.zip` is superseded and NCES's own file index no longer lists it; the two differ in exactly two columns, which spell state names out rather than abbreviating them. Still tab-delimited, and the state identifier column is renamed `ST_LEAID` here while its contents stay bare digits.",
        },
        Source {
            key: "ccd-lea-directory-1516",
            title: None,
            url: "https://nces.ed.gov/ccd/data/zip/ccd_lea_029_1516_w_1a_011717_csv.zip",
            filename: "ccd-lea-directory-1516.zip",
            format: Format::Zip,
            catalog: Some("nces-ccd-lea-directory"),
            fixtures: &[crate::fixtures::CCD_DIRECTORY_FIXTURE],
            note: "School year 2015-16. The first comma-delimited year, and the last one whose `ST_LEAID` is a bare IRN.",
        },
        Source {
            key: "ccd-lea-directory-1617",
            title: None,
            url: "https://nces.ed.gov/ccd/data/zip/ccd_lea_029_1617_w_1a_11212017_csv.zip",
            filename: "ccd-lea-directory-1617.zip",
            format: Format::Zip,
            catalog: Some("nces-ccd-lea-directory"),
            fixtures: &[crate::fixtures::CCD_DIRECTORY_FIXTURE],
            note: "School year 2016-17. The year the `OH-` prefix appears on `ST_LEAID`. The combined `..._11212017.zip` holds the same CSV byte for byte alongside a SAS file; this is the smaller archive of the two and NCES's index lists it.",
        },
        Source {
            key: "ccd-lea-directory-1718",
            title: None,
            url: "https://nces.ed.gov/ccd/data/zip/ccd_lea_029_1718_w_1a_083118.zip",
            filename: "ccd-lea-directory-1718.zip",
            format: Format::Zip,
            catalog: Some("nces-ccd-lea-directory"),
            fixtures: &[crate::fixtures::CCD_DIRECTORY_FIXTURE],
            note: "School year 2017-18. Carries the CSV beside a `.sas7bdat` of the same directory, which is why the member is chosen by suffix rather than by name.",
        },
        Source {
            key: "ccd-lea-directory-1819",
            title: None,
            url: "https://nces.ed.gov/ccd/data/zip/ccd_lea_029_1819_l_1a_091019.zip",
            filename: "ccd-lea-directory-1819.zip",
            format: Format::Zip,
            catalog: Some("nces-ccd-lea-directory"),
            fixtures: &[crate::fixtures::CCD_DIRECTORY_FIXTURE],
            note: "School year 2018-19. The final release. The preliminary `..._0a_04082019_csv.zip` is a different file and NCES's index no longer lists it; for Ohio they carry the same 1,074 agencies with the same statuses. Note the URL says `_l_` and the CSV inside says `_w_`.",
        },
        Source {
            key: "ccd-lea-directory-1920",
            title: None,
            url: "https://nces.ed.gov/ccd/data/zip/ccd_lea_029_1920_w_1a_082120.zip",
            filename: "ccd-lea-directory-1920.zip",
            format: Format::Zip,
            catalog: Some("nces-ccd-lea-directory"),
            fixtures: &[crate::fixtures::CCD_DIRECTORY_FIXTURE],
            note: "School year 2019-20. From here the header is 58 columns in a fixed order and does not move again.",
        },
        Source {
            key: "ccd-lea-directory-2021",
            title: None,
            url: "https://nces.ed.gov/ccd/data/zip/ccd_lea_029_2021_w_1a_080621.zip",
            filename: "ccd-lea-directory-2021.zip",
            format: Format::Zip,
            catalog: Some("nces-ccd-lea-directory"),
            fixtures: &[crate::fixtures::CCD_DIRECTORY_FIXTURE],
            note: "School year 2020-21. Not UTF-8: a cp1252 en dash sits in an Arkansas agency's name. Every file here is read Latin-1 byte for byte, because a lossy read would put a replacement character into committed data.",
        },
        Source {
            key: "ccd-lea-directory-2122",
            title: None,
            url: "https://nces.ed.gov/ccd/data/zip/ccd_lea_029_2122_w_1a_071722.zip",
            filename: "ccd-lea-directory-2122.zip",
            format: Format::Zip,
            catalog: Some("nces-ccd-lea-directory"),
            fixtures: &[crate::fixtures::CCD_DIRECTORY_FIXTURE],
            note: "School year 2021-22. One Ohio agency closes this year, which is the fewest in the window.",
        },
        Source {
            key: "ccd-lea-directory-2324",
            title: None,
            url: "https://nces.ed.gov/ccd/data/zip/ccd_lea_029_2324_w_1a_073124.zip",
            filename: "ccd-lea-directory-2324.zip",
            format: Format::Zip,
            catalog: Some("nces-ccd-lea-directory"),
            fixtures: &[crate::fixtures::CCD_DIRECTORY_FIXTURE],
            note: "School year 2023-24. The latest published, and the year the departure count returns to twelve.",
        },
        Source {
            key: "ccd-lea-directory-2223",
        title: None,
        url: "https://nces.ed.gov/ccd/data/zip/ccd_lea_029_2223_w_1a_083023.zip",
        filename: "ccd-lea-directory-2223.zip",
        format: Format::Zip,
        catalog: Some("nces-ccd-lea-directory"),
        fixtures: &[
            crate::fixtures::F33_DISTRICTS_FIXTURE,
            crate::fixtures::CROSSWALK_FIXTURE,
            crate::fixtures::F33_OHIO_PANEL_FIXTURE,
            crate::fixtures::CCD_DIRECTORY_FIXTURE,
        ],
        note: "`ST_LEAID` is the Ohio IRN behind an `OH-` prefix, and `LEAID` is the NCES \
               agency identifier whose last five digits are the Census school district code. \
               All 609 districts in the funding panel join through it. This is the \
               NCESID-to-IRN crosswalk `census-f33` records as missing and \
               `census-geography` needs. School year 2022-23, and the year every other \
               fixture here resolves an IRN through — which is what made it worth asking \
               what the other fifteen years say.",
        },
    ],
};
